---
title: "M8 Problem Set: Dependent t-test for TAs"
author: "Pablo E. Gutiérrez-Fonseca"
date: "2024-03-23"
output: pdf_document
---

Now we will move on to the Butterfly Babies Data. 
Assume that we want to test to see if there is a difference between butterfly wing length for the 
parents treated with pesticides (generation 1) and their offspring (generation 2).   
Use an alpha level of 0.05 
Write a concise one paragraph summary of this analysis. 


#1. Import libraries and load packages
```{r message=FALSE}
library(tidyverse)
library(lessR)
library(readxl)
library(BSDA)
```


#2. importing our data
```{r}
butterflies <- read_excel("butterflies_babies.xlsx")
```

```{r}
t.test(wing_length ~ Generation, data=butterflies,
       alternative = "two.sided",
       mu = 0, 
       paired = TRUE,   
       var.equal = TRUE,
       conf.level = 0.95)
```


Cohen's
```{r}
# Calcular la diferencia entre Generation_2 y Generation_1
difference <- butterflies$wing_length[butterflies$Generation == "Generation_2"] - 
              butterflies$wing_length[butterflies$Generation == "Generation_1"]

# Calcular la desviación estándar de la diferencia
sd_difference <- sd(difference)

# Calcular Cohen's d
cohens_d <- mean(difference) / sd_difference

# Imprimir Cohen's d
print(cohens_d)
```

